# Regular address name record
address=/alice/10.200.0.2
address=/bob/10.200.0.3

# SRV records
# srv-host=_service._proto.name,target,port
srv-host=_minecraft._tcp.alice,alice,25565
srv-host=_http._tcp.bob,bob,80
srv-host=_https._tcp.bob,bob,443

# Podman internal DNS gateway
server=/node1.internal/10.100.0.1

# systemctl reload dnsmasq