[Interface]
ListenPort = 50001
#PrivateKey = <contents of /root/wireguard/wg-mesh-private.key>
PostUp = wg set wg-mesh private-key /root/wireguard/wg-mesh-private.key
PostUp = wg addconf wg-mesh /root/wireguard/wg-mesh-peers.conf
PostUp = iptables -A FORWARD -i wg-mesh -j ACCEPT
PostUp = iptables -A FORWARD -o wg-mesh -j ACCEPT
PostUp = iptables -t nat -A POSTROUTING -s 10.100.0.0/24 -j MASQUERADE
PreDown = iptables -D FORWARD -i wg-mesh -j ACCEPT
PreDown = iptables -D FORWARD -o wg-mesh -j ACCEPT
PreDown = iptables -t nat -D POSTROUTING -s 10.100.0.0/24 -j MASQUERADE