[Interface]
ListenPort = 50002
#PrivateKey = <contents of /root/wireguard/wg-net-private.key>
PostUp = wg set wg-net private-key /root/wireguard/wg-net-private.key
PostUp = wg addconf wg-net /root/wireguard/wg-net-peers.conf
PostUp = iptables -A FORWARD -i wg-net -j ACCEPT
PostUp = iptables -A FORWARD -o wg-net -j ACCEPT
PostUp = iptables -t nat -A POSTROUTING -s 10.200.0.0/24 -j MASQUERADE
PreDown = iptables -D FORWARD -i wg-net -j ACCEPT
PreDown = iptables -D FORWARD -o wg-net -j ACCEPT
PreDown = iptables -t nat -D POSTROUTING -s 10.200.0.0/24 -j MASQUERADE