### Server side
# wg-mesh

# XAN01
[Peer]
PublicKey = PUBLIC_KEY
Endpoint = DOMAIN_NAME:PORT
AllowedIPs = 10.100.0.1/32

# XAN02
[Peer]
PublicKey = PUBLIC_KEY
Endpoint = DOMAIN_NAME:PORT
AllowedIPs = 10.100.0.2/32

# TSU01
[Peer]
PublicKey = PUBLIC_KEY
Endpoint = DOMAIN_NAME:PORT
AllowedIPs = 10.100.0.3/32

# wg-net

# xanedithas
[Peer]
PublicKey = PUBLIC_KEY
AllowedIPs = 10.200.0.11/32

# mikes
[Peer]
PublicKey = PUBLIC_KEY
AllowedIPs = 10.200.0.12/32

# tsukia
[Peer]
PublicKey = PUBLIC_KEY
AllowedIPs = 10.200.0.31/32

### Client side
# wg-net

[Interface]
PrivateKey = PRIVATE_KEY
Address = 10.200.0.XXX
DNS = 10.200.0.1

# XAN01
[Peer]
PublicKey = REPLACE_ME
Endpoint = DOMAIN_NAME:PORT
AllowedIPs = 10.200.0.1, 10.200.0.0/24
PersistentKeepalive = 25

# TSU01
# Add AllowedIPs ", 10.200.0.0/24" when it makes sense
[Peer]
PublicKey = REPLACE_ME
Endpoint = DOMAIN_NAME:PORT
AllowedIPs = 10.200.0.3
PersistentKeepalive = 25
