[Peer]
PublicKey = REPLACE_ME_XAN02
AllowedIPs = 10.100.0.1/32

[Peer]
PublicKey = REPLACE_ME_TSU01
AllowedIPs = 10.100.0.3/32

[Peer]
PublicKey = REPLACE_ME
Endpoint = datahuys.nl:51820
AllowedIPs = 10.200.0.0/24
PersistentKeepalive = 25
; TODO: change domain name for remote host
