usernames  # require username and password for login
chpw  # allow users to change their own passwords
ah-alg: argon2  # password hashing algorithm: argon2 scrypt sha2 none

[global]
  e2dsa  # scan and index all files in all volumes on startup
  e2ts  # check newly-discovered or uploaded files for media tags
  ansi  # enable colors in log messages (both in logfiles and stdout)
  dedup  # enable deduplication
  reflink  # copy-on-write
#  no-dupe  # prevent duplicate uploads
  no-robots  # hiding from bots like google
  hist: ~/.cache/copyparty  # put db / thumbs / etc. here
  th-crop: y  # center-cropping (y/n/fy/fn)
  th-x3: y  # thumbs 3x resolution (y/n/fy/fn)
  grid  # show grid/thumbnails by default
  vc-url: https://api.copyparty.eu/advisories
  vc-age: 6  # how many hours to wait between each check
  vc-exit  # emergency-exit if current version is vulnerable
  df: 16  # stop accepting uploads if less than 16 GB free space
  name: XAN01  # service name in browser

[accounts]
  xanedithas: 123  # username: password

[/]  # create a volume at "/"
  /w  # share /w (the docker data volume)
  accs:
    rwmda: xanedithas  # read-write-move-delete-admin