pageInfo:
  title: Comfort Zone
  description: Here be dragons!
  navLinks:
    - title: GitHub
      path: https://github.com/Tsukia22/nixos
      target: newtab
  footerText: © 2025 My Dashboard — Built with ♥ and coffee
  logo: >-
    https://static.wikia.nocookie.net/pkmnshuffle/images/5/5a/Dragonair.png/revision/latest?cb=20170407191603
appConfig:
  theme: colorful
  layout: auto
  iconSize: medium
  auth:
    enableGuestAccess: true
    users:
      - user: Tsukia
        hash: 92c7fa28bfd037328544cce72bbbaf4dd604104939ca04d3778ac83b357b7697
        type: admin
      - user: Xanedithas
        hash: fdf61680a7710d7b87277321faa57fb5c1545f2231902fbfacb5dcb0e1245276
        type: admin
    enableHeaderAuth: false
    headerAuth:
      userHeader: REMOTE_USER
      proxyWhitelist: []
    enableKeycloak: false
  startingView: default
  defaultOpeningMethod: newtab
  statusCheck: true
  statusCheckInterval: 0
  faviconApi: allesedv
  routingMode: history
  enableMultiTasking: false
  widgetsAlwaysUseProxy: false
  webSearch:
    disableWebSearch: false
    searchEngine: google
    openingMethod: newtab
    searchBangs: {}
  enableFontAwesome: true
  enableMaterialDesignIcons: true
  hideComponents:
    hideHeading: false
    hideNav: false
    hideSearch: false
    hideSettings: false
    hideFooter: false
  showSplashScreen: false
  preventWriteToDisk: false
  preventLocalSave: false
  disableConfiguration: false
  disableConfigurationForNonAdmin: false
  allowConfigEdit: true
  enableServiceWorker: false
  disableContextMenu: false
  disableUpdateChecks: false
  disableSmartSort: false
  enableErrorReporting: false
sections:
  - name: Public Services
    displayData:
      sortBy: default
      rows: 2
      cols: 3
      collapsed: false
      hideForGuests: false
    items: []
    icon: fas fa-globe
    filteredItems: []
  - name: Internal Services
    displayData:
      sortBy: default
      rows: 2
      cols: 1
      collapsed: false
      hideForGuests: true
    items:
      - &ref_0
        title: Dockge
        icon: https://cdn.jsdelivr.net/gh/selfhst/icons/webp/dockge.webp
        url: http://192.168.1.34:25560/
        target: newtab
        statusCheck: true
        id: 0_1697_dockge
      - &ref_1
        title: Traefik
        icon: https://cdn.jsdelivr.net/gh/selfhst/icons/webp/traefik.webp
        url: http://192.168.1.34:25561
        statusCheck: true
        id: 1_1697_traefik
    icon: fas fa-wrench
    filteredItems:
      - *ref_0
      - *ref_1
  - name: Monitoring
    displayData:
      sortBy: default
      rows: 2
      cols: 1
      collapsed: false
      hideForGuests: false
    widgets:
      - id: 0_1062_uptimekuma
        type: uptime-kuma
        useProxy: true
        options:
          url: https://up.tsukia.nl/metrics
          apiKey: 
    icon: fas fa-desktop
    items:
      - &ref_2
        title: Uptime Kuma
        icon: https://cdn.jsdelivr.net/gh/selfhst/icons/webp/uptime-kuma.webp
        url: https://up.tsukia.nl/status/games
        target: newtab
        id: 0_1062_uptimekuma
    filteredItems:
      - *ref_2
  - name: Media
    displayData:
      sortBy: default
      rows: 2
      cols: 1
      collapsed: false
      hideForGuests: false
    items: []
    icon: fas fa-tag
    filteredItems: []
  - name: Entertainment
    displayData:
      sortBy: default
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
    items: []
    icon: fas fa-link
    filteredItems: []
  - name: Storage & SFTP
    displayData:
      sortBy: default
      rows: 2
      cols: 1
      collapsed: false
      hideForGuests: false
    items:
      - &ref_3
        title: SFTPGo
        icon: https://cdn.jsdelivr.net/gh/selfhst/icons/webp/sftpgo.webp
        url: https://sftp.tsukia.nl
        statusCheck: true
        id: 0_1144_sftpgo
    icon: fas fa-suitcase
    filteredItems:
      - *ref_3
